import mongoose from 'mongoose';const environmentalDataSchema = new mongoose.Schema({    location: {        type: {            type: String,            enum: ['Point'],            required: true        },        coordinates: {            type: [Number], 
            required: true        }    },    soilData: {        type: {            type: String,            enum: ['clay', 'sandy', 'loamy', 'silty', 'peaty', 'chalky'],            required: true        },        pH: {            type: Number,            required: true,            min: 0,            max: 14        },        organicMatter: {            type: Number, 
            min: 0,            max: 100        },        drainage: {            type: String,            enum: ['poor', 'moderate', 'good', 'excellent']        }    },    climateData: {        averageRainfall: {            type: Number, 
            required: true        },        temperatureRange: {            min: Number, 
            max: Number  
        },        humidity: {            type: Number, 
            min: 0,            max: 100        },        climateZone: {            type: String,            enum: ['tropical', 'subtropical', 'temperate', 'arid', 'semi-arid']        }    },    riskFactors: [{        type: {            type: String,            enum: ['drought', 'flood', 'fire', 'frost', 'pest', 'disease']        },        probability: {            type: String,            enum: ['low', 'medium', 'high']        },        season: String 
    }],    dataSource: {        type: String,        enum: ['api', 'manual', 'mock'],        default: 'mock'    },    lastUpdated: {        type: Date,        default: Date.now    }}, {    timestamps: true});environmentalDataSchema.index({ location: '2dsphere' });environmentalDataSchema.statics.findNearLocation = async function (longitude, latitude, maxDistance = 50000) {    return await this.findOne({        location: {            $near: {                $geometry: {                    type: 'Point',                    coordinates: [longitude, latitude]                },                $maxDistance: maxDistance 
            }        }    });};environmentalDataSchema.statics.getOrCreateForLocation = async function (longitude, latitude) {    let envData = await this.findNearLocation(longitude, latitude);    if (envData) {        return envData;    }    const mockData = {        location: {            type: 'Point',            coordinates: [longitude, latitude]        },        soilData: {            type: 'loamy', 
            pH: 6.5,            organicMatter: 3.5,            drainage: 'good'        },        climateData: {            averageRainfall: 1200, 
            temperatureRange: {                min: 15,                max: 35            },            humidity: 65,            climateZone: 'subtropical'        },        riskFactors: [            {                type: 'drought',                probability: 'medium',                season: 'summer'            }        ],        dataSource: 'mock'    };    envData = await this.create(mockData);    return envData;};const EnvironmentalData = mongoose.model('EnvironmentalData', environmentalDataSchema);export default EnvironmentalData;